spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/usedbook
    driver-class-name: org.mariadb.jdbc.Driver
    username: usedbookroot
    password: 1234


mybatis:
  type-aliases-package: team.hello.usedbook.domain
  mapper-locations: mybatis/**.xml


server:
  servlet:
    session:
      timeout: 30m  # 기본값은 30m(30분) m을 붙이지 않으면 초단위로 설정됨. 최소 60초 이상일 것
      tracking-modes: cookie  #최초접속 시 url에 jsession안붙게