spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/usedbook
    driver-class-name: org.mariadb.jdbc.Driver
    username: usedbookroot
    password: 1234


mybatis:
  type-aliases-package: team.hello.usedbook.domain
  mapper-locations: mybatis/**.xml